name: Setup Homebrew Tap

on:
  workflow_dispatch:
    inputs:
      create_repo:
        description: 'Create tap repository if it does not exist'
        required: true
        default: 'true'

jobs:
  setup-tap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create tap repository
        if: ${{ github.event.inputs.create_repo == 'true' }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const { data } = await github.rest.repos.get({
                owner: context.repo.owner,
                repo: 'homebrew-cpw'
              });
              console.log('Tap repository already exists');
            } catch (error) {
              if (error.status === 404) {
                console.log('Creating tap repository...');
                const { data } = await github.rest.repos.createInOrg({
                  org: context.repo.owner,
                  name: 'homebrew-cpw',
                  description: 'Homebrew tap for CPW - Copy on Write file watcher',
                  private: false,
                  auto_init: true
                });
                console.log('Tap repository created: ' + data.html_url);
              } else {
                console.error('Error checking repository:', error);
                process.exit(1);
              }
            }

      - name: Setup Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Clone tap repository
        run: |
          git clone https://github.com/${{ github.repository_owner }}/homebrew-cpw.git tap

      - name: Create formula directory
        run: |
          mkdir -p tap/Formula

      - name: Copy formula template
        run: |
          cp Formula/cpw.rb tap/Formula/

      - name: Commit and push
        working-directory: ./tap
        run: |
          git add Formula/cpw.rb
          git commit -m "Initial formula setup" || echo "No changes to commit"
          git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository_owner }}/homebrew-cpw.git
